### ISSUE TITLE
Xbox 360 wireless adapter

### ISSUE THREAD

**Issue by raidernick** [wiredopposite/OGX-Mini#19]
While this adapter does work there are two issues with it. The first issue is that the controller ring will constantly flash as if it's not connected to the adapter while it is in fact connected. This is a minor annoyance but it would be nice if it displayed that it was connected to player one correctly.

The second issue is that the right rumble motor does not work. The left rumble works just fine but the right does not.

**Comment by wiredopposite** [comment]
Thanks for reporting, I have fixes for both of these in v0.4 coming later today

**Comment by raidernick** [comment]
fixed now thanks
