### ISSUE TITLE
VID/PID for Sony Sixaxis (PS3/Dualshock 3 predecessor)

### ISSUE THREAD

**Issue by Darthagnon** [wiredopposite/OGX-Mini#2]
I've got 3 Sixaxis controllers CECHZC1E. Here's VID/PID info, as requested in the Readme (retrieved using DsHidMini on my PC)
```
USB\VID_054C&PID_0268
```
Seems to be the same for each one as I plug it in; am using Nefarius' drivers.

**Comment by wiredopposite** [comment]
Thanks, I'll be adding support most likely in the next update
