### ISSUE TITLE
v0.4.0

### ISSUE THREAD

**Issue by Androxilogin** [wiredopposite/OGX-Mini#24]
I just had one heck of a time with this. It seems the 2040-Zero file doesn't work on the Zero, the regular one does.

**Comment by wiredopposite** [comment]
Hey the usb pins are different for the rp2040-zero file, data +/- are GPIO 10 and 11, did you have the port hooked up to those?

**Comment by Androxilogin** [comment]
Actually, no! I was unaware of that. It worked with the regular pins with the other file on the RP2040-Zero. Is there a consequence in using it this way? I'll switch them over now, regardless but it seems to work this way.

**Comment by wiredopposite** [comment]
No there's no difference between either firmware except the pins, I just changed them for the RP2040-Zero so you can attach the USB A port to the end opposite the USB C port. Also for the custom PCB in the [hardware folder](https://github.com/wiredopposite/OGX-Mini/tree/master/hardware).

**Comment by Androxilogin** [comment]
Ah, I see. Working as intended. Awesome project!
