### ISSUE TITLE
Quick swap A and B buttons

### ISSUE THREAD

**Issue by Invictaz** [wiredopposite/OGX-Mini#26]
As there is no webUI to have remap, or a Windows utility or GUI or something else, the only option to have A and B swapped for Nintendo use is to recompile ogx-mini which is quite a hassle. 

For example if you have 

X as confirm button working on xinput, ps3, psclassic mode you also have it on Nintendo Switch output. But they use Circle as confirm.

Solution:

make a button combination to swap Circle and Cross on the fly in Nintendo Switch mode. Maybe select and both shoulder buttons?

**Comment by radu-gs** [comment]
A profile feature would be pretty useful. I'd also like something similar for playing PS3 games with an Xbox controller, as many games have L1/R1 swapped with L2/R2 due to the DS3's weird triggers.
