### ISSUE TITLE
VID/PID for Nintendo Controllers

### ISSUE THREAD

**Issue by Invictaz** [wiredopposite/OGX-Mini#4]
List of Nintendo PID and VID's for support

https://the-sz.com/products/usbid/index.php?v=0x057E

Implementations:

https://github.com/Dan611/hid-procon

https://github.com/TheWaveWarden/SwitchProConLinuxUSB

Remember some projects (just like steam) also check for the name of the controller

https://discourse.libsdl.org/t/sdl-dont-rely-on-the-device-vid-pid-to-get-the-nintendo-controller-type/38067

**Comment by wiredopposite** [comment]
Switch Pro and wired PowerA controller support have been added in v0.2.0

**Comment by Invictaz** [comment]
Great
