### ISSUE TITLE
Mount LED not working with RP2040 Zero + Interposer Board

### ISSUE THREAD

**Issue by SRDWA** [wiredopposite/OGX-Mini#45]
Hello,
as you can read in the title, the mount/unmount LED is not working.

I have already found the error. See screenshot.
The LED on the interposer board is connected to GPIO 14 and not GPIO 13.
Unfortunately I cannot compile the firmware myself.
I would like a correction.

Kind regards, Sven

![Screenshot 2024-10-09 202108](https://github.com/user-attachments/assets/c59b25fa-c2b0-4169-be82-61cc201e3800)

**Comment by danko79** [comment]
Yes, i have a same problem.

**Comment by Dean24769** [comment]
Use a jump wire from 5v on the chip to pin 14 to bypass

**Comment by SRDWA** [comment]
@Dean
But your solution is not correct.
1. You would permanently destroy the GPIO 14 output in the microcontroller!
2. The LED would be permanently lit.

My temporary solution is:
Cut the trace between GPIO 13 and the resistor R3.
I used a 1mm drill bit for this.
Then connect R3 to GPIO 13 with a jumper wire.

Pictures follow.

**Comment by SRDWA** [comment]
![20241019_092250](https://github.com/user-attachments/assets/d4f44cfa-b6a6-48a4-be8d-af8255a8e4f4)
![20241019_092432](https://github.com/user-attachments/assets/092234b0-3acd-4f46-9a36-1b275791860b)

**Comment by danko79** [comment]
ok for the solution, but I didn't understand if the problem is in the pcb or in the firmware?

**Comment by SRDWA** [comment]
Which came first, the chicken or the egg?

I think the firmware was there first. So the error is on the interposer PCB.
I can only see 2 solutions to fix the problem.
1. Either the interposer PCB is changed and the LED is connected to GPIO 13, or
2. An agreement is reached and GPIO 14 is used in future firmwares.

As there seems to be no official support here, I have chosen the hardware solution. I am unable to fix the error on the software level.

**Comment by danko79** [comment]
> Which came first, the chicken or the egg?
> 
> I think the firmware was there first. So the error is on the interposer PCB. I can only see 2 solutions to fix the problem.
> 
>     1. Either the interposer PCB is changed and the LED is connected to GPIO 13, or
> 
>     2. An agreement is reached and GPIO 14 is used in future firmwares.
> 
> 
> As there seems to be no official support here, I have chosen the hardware solution. I am unable to fix the error on the software level.

Let's hope you update the firmware then I don't want to modify the pcb.
Thanks

**Comment by AR1972** [comment]
I fixed this
https://github.com/AR1972/OGX-Mini/releases

**Comment by danko79** [comment]
> I fixed this https://github.com/AR1972/OGX-Mini/releases

Works fine! Many thanks.

**Comment by wiredopposite** [comment]
The new firmware sets the correct pin now, and also the rgb led on there
