### ISSUE TITLE
8bitdo Ultimate C Wired not working

### ISSUE THREAD

**Issue by mastercheff** [wiredopposite/OGX-Mini#46]
**Describe the bug**
8bitdo Ultimate C Wired controller is not working for me,  newer Ultimate 2C is working great though . Home button diode blinks so it's at least getting power

**What type of controller do you have the issue with?**
8bitdo Ultimate C Wired

Device Manager throws this as HW ids :

USB\VID_2DC8&PID_3106&REV_0114
USB\VID_2DC8&PID_3106

**What platform are you using the OGX-Mini on?**
 OG Xbox, PC

**What board are you using?**
RP2040-Zero , Unit behaved well with both Xbox and PC in XInput mode

On a side note : gamepad is working great with MisterFPGA

**Comment by Invictaz** [comment]
Would you be able to do a USB descriptor dump and post it here?

**Comment by mastercheff** [comment]
the pad is at my Buddys rn, will get to it eventually, rather soon

**Comment by mastercheff** [comment]
closed, looks duplicate with #58
