### ISSUE TITLE
Wireless Adapter USB Receiver For Xbox One Not working

### ISSUE THREAD

**Issue by danko79** [wiredopposite/OGX-Mini#62]
Hi, i bought this Wireless Adapter USB Receiver For Xbox One
https://www.aliexpress.com/item/1005006105030394.html?spm=a2g0o.order_list.order_list_main.15.4c6f1802dPqUqg

And updated the firmware OGX-Mini-v1.0.0a-RP_ZERO.uf2 but it still doesn't work, not even its LED lights up, is there any chance of making it work?

**Comment by Invictaz** [comment]
See #14

**Comment by wiredopposite** [comment]
This hasn't been implemented or said to work so I'm gonna close this, support maybe added in a future update
